// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientMessage.proto

package com.message;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET = 1;</code>
     */
    GET(0, 1),
    /**
     * <code>POST = 2;</code>
     */
    POST(1, 2),
    /**
     * <code>PUT = 3;</code>
     */
    PUT(2, 3),
    /**
     * <code>DELETE = 4;</code>
     */
    DELETE(3, 4),
    ;

    /**
     * <code>GET = 1;</code>
     */
    public static final int GET_VALUE = 1;
    /**
     * <code>POST = 2;</code>
     */
    public static final int POST_VALUE = 2;
    /**
     * <code>PUT = 3;</code>
     */
    public static final int PUT_VALUE = 3;
    /**
     * <code>DELETE = 4;</code>
     */
    public static final int DELETE_VALUE = 4;


    public final int getNumber() { return value; }

    public static Operation valueOf(int value) {
      switch (value) {
        case 1: return GET;
        case 2: return POST;
        case 3: return PUT;
        case 4: return DELETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.message.ClientMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Operation(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Operation)
  }

  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Operation operation = 5;</code>
     *
     * <pre>
     * define operation in the request message
     * </pre>
     */
    boolean hasOperation();
    /**
     * <code>optional .Operation operation = 5;</code>
     *
     * <pre>
     * define operation in the request message
     * </pre>
     */
    com.message.ClientMessage.Operation getOperation();

    /**
     * <code>optional string key = 6;</code>
     *
     * <pre>
     * key for chunk sent by the client
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 6;</code>
     *
     * <pre>
     * key for chunk sent by the client
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 6;</code>
     *
     * <pre>
     * key for chunk sent by the client
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional bytes data = 7;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 7;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional int32 seq_no = 8;</code>
     */
    boolean hasSeqNo();
    /**
     * <code>optional int32 seq_no = 8;</code>
     */
    int getSeqNo();

    /**
     * <code>optional .ChunkInfo chunkInfo = 16;</code>
     */
    boolean hasChunkInfo();
    /**
     * <code>optional .ChunkInfo chunkInfo = 16;</code>
     */
    com.message.ClientMessage.ChunkInfo getChunkInfo();
    /**
     * <code>optional .ChunkInfo chunkInfo = 16;</code>
     */
    com.message.ClientMessage.ChunkInfoOrBuilder getChunkInfoOrBuilder();
  }
  /**
   * Protobuf type {@code RequestMessage}
   */
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RequestMessage)
      RequestMessageOrBuilder {
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestMessage defaultInstance;
    public static RequestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RequestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.message.ClientMessage.Operation value = com.message.ClientMessage.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = value;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              key_ = bs;
              break;
            }
            case 58: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000008;
              seqNo_ = input.readInt32();
              break;
            }
            case 130: {
              com.message.ClientMessage.ChunkInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = chunkInfo_.toBuilder();
              }
              chunkInfo_ = input.readMessage(com.message.ClientMessage.ChunkInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chunkInfo_);
                chunkInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.ClientMessage.internal_static_RequestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.ClientMessage.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.message.ClientMessage.RequestMessage.class, com.message.ClientMessage.RequestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestMessage> PARSER =
        new com.google.protobuf.AbstractParser<RequestMessage>() {
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 5;
    private com.message.ClientMessage.Operation operation_;
    /**
     * <code>optional .Operation operation = 5;</code>
     *
     * <pre>
     * define operation in the request message
     * </pre>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Operation operation = 5;</code>
     *
     * <pre>
     * define operation in the request message
     * </pre>
     */
    public com.message.ClientMessage.Operation getOperation() {
      return operation_;
    }

    public static final int KEY_FIELD_NUMBER = 6;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 6;</code>
     *
     * <pre>
     * key for chunk sent by the client
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string key = 6;</code>
     *
     * <pre>
     * key for chunk sent by the client
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 6;</code>
     *
     * <pre>
     * key for chunk sent by the client
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 7;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes data = 7;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int SEQ_NO_FIELD_NUMBER = 8;
    private int seqNo_;
    /**
     * <code>optional int32 seq_no = 8;</code>
     */
    public boolean hasSeqNo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 seq_no = 8;</code>
     */
    public int getSeqNo() {
      return seqNo_;
    }

    public static final int CHUNKINFO_FIELD_NUMBER = 16;
    private com.message.ClientMessage.ChunkInfo chunkInfo_;
    /**
     * <code>optional .ChunkInfo chunkInfo = 16;</code>
     */
    public boolean hasChunkInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .ChunkInfo chunkInfo = 16;</code>
     */
    public com.message.ClientMessage.ChunkInfo getChunkInfo() {
      return chunkInfo_;
    }
    /**
     * <code>optional .ChunkInfo chunkInfo = 16;</code>
     */
    public com.message.ClientMessage.ChunkInfoOrBuilder getChunkInfoOrBuilder() {
      return chunkInfo_;
    }

    private void initFields() {
      operation_ = com.message.ClientMessage.Operation.GET;
      key_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      seqNo_ = 0;
      chunkInfo_ = com.message.ClientMessage.ChunkInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasChunkInfo()) {
        if (!getChunkInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(5, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(6, getKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(7, data_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(8, seqNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(16, chunkInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, data_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, seqNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, chunkInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.message.ClientMessage.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.message.ClientMessage.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.message.ClientMessage.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.ClientMessage.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.ClientMessage.RequestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMessage)
        com.message.ClientMessage.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.ClientMessage.internal_static_RequestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.ClientMessage.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.message.ClientMessage.RequestMessage.class, com.message.ClientMessage.RequestMessage.Builder.class);
      }

      // Construct using com.message.ClientMessage.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChunkInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        operation_ = com.message.ClientMessage.Operation.GET;
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        seqNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (chunkInfoBuilder_ == null) {
          chunkInfo_ = com.message.ClientMessage.ChunkInfo.getDefaultInstance();
        } else {
          chunkInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.ClientMessage.internal_static_RequestMessage_descriptor;
      }

      public com.message.ClientMessage.RequestMessage getDefaultInstanceForType() {
        return com.message.ClientMessage.RequestMessage.getDefaultInstance();
      }

      public com.message.ClientMessage.RequestMessage build() {
        com.message.ClientMessage.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.message.ClientMessage.RequestMessage buildPartial() {
        com.message.ClientMessage.RequestMessage result = new com.message.ClientMessage.RequestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seqNo_ = seqNo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (chunkInfoBuilder_ == null) {
          result.chunkInfo_ = chunkInfo_;
        } else {
          result.chunkInfo_ = chunkInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.ClientMessage.RequestMessage) {
          return mergeFrom((com.message.ClientMessage.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.message.ClientMessage.RequestMessage other) {
        if (other == com.message.ClientMessage.RequestMessage.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000002;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSeqNo()) {
          setSeqNo(other.getSeqNo());
        }
        if (other.hasChunkInfo()) {
          mergeChunkInfo(other.getChunkInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasChunkInfo()) {
          if (!getChunkInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.message.ClientMessage.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.message.ClientMessage.RequestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.message.ClientMessage.Operation operation_ = com.message.ClientMessage.Operation.GET;
      /**
       * <code>optional .Operation operation = 5;</code>
       *
       * <pre>
       * define operation in the request message
       * </pre>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Operation operation = 5;</code>
       *
       * <pre>
       * define operation in the request message
       * </pre>
       */
      public com.message.ClientMessage.Operation getOperation() {
        return operation_;
      }
      /**
       * <code>optional .Operation operation = 5;</code>
       *
       * <pre>
       * define operation in the request message
       * </pre>
       */
      public Builder setOperation(com.message.ClientMessage.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Operation operation = 5;</code>
       *
       * <pre>
       * define operation in the request message
       * </pre>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = com.message.ClientMessage.Operation.GET;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 6;</code>
       *
       * <pre>
       * key for chunk sent by the client
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string key = 6;</code>
       *
       * <pre>
       * key for chunk sent by the client
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 6;</code>
       *
       * <pre>
       * key for chunk sent by the client
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 6;</code>
       *
       * <pre>
       * key for chunk sent by the client
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 6;</code>
       *
       * <pre>
       * key for chunk sent by the client
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 6;</code>
       *
       * <pre>
       * key for chunk sent by the client
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 7;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes data = 7;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 7;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 7;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int seqNo_ ;
      /**
       * <code>optional int32 seq_no = 8;</code>
       */
      public boolean hasSeqNo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 seq_no = 8;</code>
       */
      public int getSeqNo() {
        return seqNo_;
      }
      /**
       * <code>optional int32 seq_no = 8;</code>
       */
      public Builder setSeqNo(int value) {
        bitField0_ |= 0x00000008;
        seqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 seq_no = 8;</code>
       */
      public Builder clearSeqNo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seqNo_ = 0;
        onChanged();
        return this;
      }

      private com.message.ClientMessage.ChunkInfo chunkInfo_ = com.message.ClientMessage.ChunkInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.message.ClientMessage.ChunkInfo, com.message.ClientMessage.ChunkInfo.Builder, com.message.ClientMessage.ChunkInfoOrBuilder> chunkInfoBuilder_;
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public boolean hasChunkInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public com.message.ClientMessage.ChunkInfo getChunkInfo() {
        if (chunkInfoBuilder_ == null) {
          return chunkInfo_;
        } else {
          return chunkInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public Builder setChunkInfo(com.message.ClientMessage.ChunkInfo value) {
        if (chunkInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chunkInfo_ = value;
          onChanged();
        } else {
          chunkInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public Builder setChunkInfo(
          com.message.ClientMessage.ChunkInfo.Builder builderForValue) {
        if (chunkInfoBuilder_ == null) {
          chunkInfo_ = builderForValue.build();
          onChanged();
        } else {
          chunkInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public Builder mergeChunkInfo(com.message.ClientMessage.ChunkInfo value) {
        if (chunkInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              chunkInfo_ != com.message.ClientMessage.ChunkInfo.getDefaultInstance()) {
            chunkInfo_ =
              com.message.ClientMessage.ChunkInfo.newBuilder(chunkInfo_).mergeFrom(value).buildPartial();
          } else {
            chunkInfo_ = value;
          }
          onChanged();
        } else {
          chunkInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public Builder clearChunkInfo() {
        if (chunkInfoBuilder_ == null) {
          chunkInfo_ = com.message.ClientMessage.ChunkInfo.getDefaultInstance();
          onChanged();
        } else {
          chunkInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public com.message.ClientMessage.ChunkInfo.Builder getChunkInfoBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getChunkInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      public com.message.ClientMessage.ChunkInfoOrBuilder getChunkInfoOrBuilder() {
        if (chunkInfoBuilder_ != null) {
          return chunkInfoBuilder_.getMessageOrBuilder();
        } else {
          return chunkInfo_;
        }
      }
      /**
       * <code>optional .ChunkInfo chunkInfo = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.message.ClientMessage.ChunkInfo, com.message.ClientMessage.ChunkInfo.Builder, com.message.ClientMessage.ChunkInfoOrBuilder> 
          getChunkInfoFieldBuilder() {
        if (chunkInfoBuilder_ == null) {
          chunkInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.message.ClientMessage.ChunkInfo, com.message.ClientMessage.ChunkInfo.Builder, com.message.ClientMessage.ChunkInfoOrBuilder>(
                  getChunkInfo(),
                  getParentForChildren(),
                  isClean());
          chunkInfo_ = null;
        }
        return chunkInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    static {
      defaultInstance = new RequestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
  }

  public interface ChunkInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChunkInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 no_of_chunks = 15;</code>
     */
    boolean hasNoOfChunks();
    /**
     * <code>required int32 no_of_chunks = 15;</code>
     */
    int getNoOfChunks();
  }
  /**
   * Protobuf type {@code ChunkInfo}
   */
  public static final class ChunkInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChunkInfo)
      ChunkInfoOrBuilder {
    // Use ChunkInfo.newBuilder() to construct.
    private ChunkInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChunkInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChunkInfo defaultInstance;
    public static ChunkInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ChunkInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChunkInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 120: {
              bitField0_ |= 0x00000001;
              noOfChunks_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.ClientMessage.internal_static_ChunkInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.ClientMessage.internal_static_ChunkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.message.ClientMessage.ChunkInfo.class, com.message.ClientMessage.ChunkInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ChunkInfo> PARSER =
        new com.google.protobuf.AbstractParser<ChunkInfo>() {
      public ChunkInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChunkInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NO_OF_CHUNKS_FIELD_NUMBER = 15;
    private int noOfChunks_;
    /**
     * <code>required int32 no_of_chunks = 15;</code>
     */
    public boolean hasNoOfChunks() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 no_of_chunks = 15;</code>
     */
    public int getNoOfChunks() {
      return noOfChunks_;
    }

    private void initFields() {
      noOfChunks_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNoOfChunks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(15, noOfChunks_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, noOfChunks_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.message.ClientMessage.ChunkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.message.ClientMessage.ChunkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.message.ClientMessage.ChunkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.ClientMessage.ChunkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.ClientMessage.ChunkInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChunkInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChunkInfo)
        com.message.ClientMessage.ChunkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.ClientMessage.internal_static_ChunkInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.ClientMessage.internal_static_ChunkInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.message.ClientMessage.ChunkInfo.class, com.message.ClientMessage.ChunkInfo.Builder.class);
      }

      // Construct using com.message.ClientMessage.ChunkInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        noOfChunks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.ClientMessage.internal_static_ChunkInfo_descriptor;
      }

      public com.message.ClientMessage.ChunkInfo getDefaultInstanceForType() {
        return com.message.ClientMessage.ChunkInfo.getDefaultInstance();
      }

      public com.message.ClientMessage.ChunkInfo build() {
        com.message.ClientMessage.ChunkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.message.ClientMessage.ChunkInfo buildPartial() {
        com.message.ClientMessage.ChunkInfo result = new com.message.ClientMessage.ChunkInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.noOfChunks_ = noOfChunks_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.ClientMessage.ChunkInfo) {
          return mergeFrom((com.message.ClientMessage.ChunkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.message.ClientMessage.ChunkInfo other) {
        if (other == com.message.ClientMessage.ChunkInfo.getDefaultInstance()) return this;
        if (other.hasNoOfChunks()) {
          setNoOfChunks(other.getNoOfChunks());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNoOfChunks()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.message.ClientMessage.ChunkInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.message.ClientMessage.ChunkInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int noOfChunks_ ;
      /**
       * <code>required int32 no_of_chunks = 15;</code>
       */
      public boolean hasNoOfChunks() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 no_of_chunks = 15;</code>
       */
      public int getNoOfChunks() {
        return noOfChunks_;
      }
      /**
       * <code>required int32 no_of_chunks = 15;</code>
       */
      public Builder setNoOfChunks(int value) {
        bitField0_ |= 0x00000001;
        noOfChunks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 no_of_chunks = 15;</code>
       */
      public Builder clearNoOfChunks() {
        bitField0_ = (bitField0_ & ~0x00000001);
        noOfChunks_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChunkInfo)
    }

    static {
      defaultInstance = new ChunkInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ChunkInfo)
  }

  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Operation operation = 9;</code>
     */
    boolean hasOperation();
    /**
     * <code>optional .Operation operation = 9;</code>
     */
    com.message.ClientMessage.Operation getOperation();

    /**
     * <code>optional bool success = 10;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 10;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional string key = 11;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 11;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 11;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional int32 chunk_no = 12;</code>
     */
    boolean hasChunkNo();
    /**
     * <code>optional int32 chunk_no = 12;</code>
     */
    int getChunkNo();

    /**
     * <code>optional string status_msg = 13;</code>
     */
    boolean hasStatusMsg();
    /**
     * <code>optional string status_msg = 13;</code>
     */
    java.lang.String getStatusMsg();
    /**
     * <code>optional string status_msg = 13;</code>
     */
    com.google.protobuf.ByteString
        getStatusMsgBytes();

    /**
     * <code>optional bytes data = 14;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 14;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code ResponseMessage}
   */
  public static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResponseMessage)
      ResponseMessageOrBuilder {
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseMessage defaultInstance;
    public static ResponseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              com.message.ClientMessage.Operation value = com.message.ClientMessage.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = value;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000002;
              success_ = input.readBool();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              key_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000008;
              chunkNo_ = input.readInt32();
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              statusMsg_ = bs;
              break;
            }
            case 114: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.ClientMessage.internal_static_ResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.ClientMessage.internal_static_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.message.ClientMessage.ResponseMessage.class, com.message.ClientMessage.ResponseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseMessage> PARSER =
        new com.google.protobuf.AbstractParser<ResponseMessage>() {
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 9;
    private com.message.ClientMessage.Operation operation_;
    /**
     * <code>optional .Operation operation = 9;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Operation operation = 9;</code>
     */
    public com.message.ClientMessage.Operation getOperation() {
      return operation_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 10;
    private boolean success_;
    /**
     * <code>optional bool success = 10;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool success = 10;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int KEY_FIELD_NUMBER = 11;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 11;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string key = 11;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 11;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNK_NO_FIELD_NUMBER = 12;
    private int chunkNo_;
    /**
     * <code>optional int32 chunk_no = 12;</code>
     */
    public boolean hasChunkNo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 chunk_no = 12;</code>
     */
    public int getChunkNo() {
      return chunkNo_;
    }

    public static final int STATUS_MSG_FIELD_NUMBER = 13;
    private java.lang.Object statusMsg_;
    /**
     * <code>optional string status_msg = 13;</code>
     */
    public boolean hasStatusMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string status_msg = 13;</code>
     */
    public java.lang.String getStatusMsg() {
      java.lang.Object ref = statusMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statusMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string status_msg = 13;</code>
     */
    public com.google.protobuf.ByteString
        getStatusMsgBytes() {
      java.lang.Object ref = statusMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 14;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 14;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes data = 14;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      operation_ = com.message.ClientMessage.Operation.GET;
      success_ = false;
      key_ = "";
      chunkNo_ = 0;
      statusMsg_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(9, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(10, success_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(11, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(12, chunkNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(13, getStatusMsgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(14, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, success_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, chunkNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getStatusMsgBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.message.ClientMessage.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.message.ClientMessage.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.message.ClientMessage.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.ClientMessage.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.ClientMessage.ResponseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseMessage)
        com.message.ClientMessage.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.ClientMessage.internal_static_ResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.ClientMessage.internal_static_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.message.ClientMessage.ResponseMessage.class, com.message.ClientMessage.ResponseMessage.Builder.class);
      }

      // Construct using com.message.ClientMessage.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        operation_ = com.message.ClientMessage.Operation.GET;
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        statusMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.ClientMessage.internal_static_ResponseMessage_descriptor;
      }

      public com.message.ClientMessage.ResponseMessage getDefaultInstanceForType() {
        return com.message.ClientMessage.ResponseMessage.getDefaultInstance();
      }

      public com.message.ClientMessage.ResponseMessage build() {
        com.message.ClientMessage.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.message.ClientMessage.ResponseMessage buildPartial() {
        com.message.ClientMessage.ResponseMessage result = new com.message.ClientMessage.ResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chunkNo_ = chunkNo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.statusMsg_ = statusMsg_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.ClientMessage.ResponseMessage) {
          return mergeFrom((com.message.ClientMessage.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.message.ClientMessage.ResponseMessage other) {
        if (other == com.message.ClientMessage.ResponseMessage.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000004;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasChunkNo()) {
          setChunkNo(other.getChunkNo());
        }
        if (other.hasStatusMsg()) {
          bitField0_ |= 0x00000010;
          statusMsg_ = other.statusMsg_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.message.ClientMessage.ResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.message.ClientMessage.ResponseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.message.ClientMessage.Operation operation_ = com.message.ClientMessage.Operation.GET;
      /**
       * <code>optional .Operation operation = 9;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Operation operation = 9;</code>
       */
      public com.message.ClientMessage.Operation getOperation() {
        return operation_;
      }
      /**
       * <code>optional .Operation operation = 9;</code>
       */
      public Builder setOperation(com.message.ClientMessage.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Operation operation = 9;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = com.message.ClientMessage.Operation.GET;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>optional bool success = 10;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool success = 10;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 10;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 10;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 11;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string key = 11;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 11;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 11;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 11;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 11;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }

      private int chunkNo_ ;
      /**
       * <code>optional int32 chunk_no = 12;</code>
       */
      public boolean hasChunkNo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 chunk_no = 12;</code>
       */
      public int getChunkNo() {
        return chunkNo_;
      }
      /**
       * <code>optional int32 chunk_no = 12;</code>
       */
      public Builder setChunkNo(int value) {
        bitField0_ |= 0x00000008;
        chunkNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 chunk_no = 12;</code>
       */
      public Builder clearChunkNo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chunkNo_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object statusMsg_ = "";
      /**
       * <code>optional string status_msg = 13;</code>
       */
      public boolean hasStatusMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string status_msg = 13;</code>
       */
      public java.lang.String getStatusMsg() {
        java.lang.Object ref = statusMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            statusMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status_msg = 13;</code>
       */
      public com.google.protobuf.ByteString
          getStatusMsgBytes() {
        java.lang.Object ref = statusMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status_msg = 13;</code>
       */
      public Builder setStatusMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        statusMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status_msg = 13;</code>
       */
      public Builder clearStatusMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        statusMsg_ = getDefaultInstance().getStatusMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status_msg = 13;</code>
       */
      public Builder setStatusMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        statusMsg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 14;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes data = 14;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 14;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 14;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResponseMessage)
    }

    static {
      defaultInstance = new ResponseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResponseMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChunkInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023clientMessage.proto\"y\n\016RequestMessage\022" +
      "\035\n\toperation\030\005 \001(\0162\n.Operation\022\013\n\003key\030\006 " +
      "\001(\t\022\014\n\004data\030\007 \001(\014\022\016\n\006seq_no\030\010 \001(\005\022\035\n\tchu" +
      "nkInfo\030\020 \001(\0132\n.ChunkInfo\"!\n\tChunkInfo\022\024\n" +
      "\014no_of_chunks\030\017 \002(\005\"\202\001\n\017ResponseMessage\022" +
      "\035\n\toperation\030\t \001(\0162\n.Operation\022\017\n\007succes" +
      "s\030\n \001(\010\022\013\n\003key\030\013 \001(\t\022\020\n\010chunk_no\030\014 \001(\005\022\022" +
      "\n\nstatus_msg\030\r \001(\t\022\014\n\004data\030\016 \001(\014*3\n\tOper" +
      "ation\022\007\n\003GET\020\001\022\010\n\004POST\020\002\022\007\n\003PUT\020\003\022\n\n\006DEL" +
      "ETE\020\004B\r\n\013com.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RequestMessage_descriptor,
        new java.lang.String[] { "Operation", "Key", "Data", "SeqNo", "ChunkInfo", });
    internal_static_ChunkInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChunkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChunkInfo_descriptor,
        new java.lang.String[] { "NoOfChunks", });
    internal_static_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResponseMessage_descriptor,
        new java.lang.String[] { "Operation", "Success", "Key", "ChunkNo", "StatusMsg", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
